version: "3"

services:
  server:
    image: nginx:1.21.6
    restart: unless-stopped
    volumes:
      - html:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.liveActionMap.rule=Host(`live-action-map.com`) || Host(`www.live-action-map.com`)
      - traefik.http.routers.liveActionMap.tls=true
      - traefik.http.routers.liveActionMap.tls.certresolver=resolver
    networks:
      - treafik

  scraper:
    image: registry.gitlab.com/h2201/project-pipelines/live-action-map:latest
    restart: unless-stopped
    volumes:
      - html:/app/dist
    environment:
      - BEARER
      - BLACKLIST_USERID
      - NOMINATIM_URL

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: always
    ports:
      - "9568:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/europe/monaco-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/monaco-updates/
      NOMINATIM_PASSWORD: NOMINATIM_PASSWORD
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

volumes:
  html:
  nominatim-data:

networks:
  treafik:
    external: true
    name: treafik_treafik
